name: micro_chat_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  path: ^1.9.0
  envied: ^0.5.4+1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  dio: ^5.6.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/ui/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
